#!/bin/bash

DB_NAME="ExchangeDataBase.db"
CREATE_CURRENCIES="CREATE TABLE IF NOT EXISTS Currencies(ID INTEGER PRIMARY KEY AUTOINCREMENT,
                                                        Code VARCHAR(3) UNIQUE,
                                                        FullName VARCHAR(50),
                                                        Sign VARCHAR(3));"
CREATE_EXCHANGE_RATES="CREATE TABLE IF NOT EXISTS ExchangeRates(ID INTEGER PRIMARY KEY AUTOINCREMENT,
                                                        BaseCurrencyId INTEGER,
                                                        TargetCurrencyId INTEGER,
                                                        Rate DECIMAL(6),
                                                        FOREIGN KEY (BaseCurrencyId) REFERENCES Currencies (ID),
                                                        FOREIGN KEY (TargetCurrencyId) REFERENCES Currencies (ID),
                                                        UNIQUE (BaseCurrencyId, TargetCurrencyId));"
INSERT_CURRENCIES="INSERT INTO Currencies(Code, FullName, Sign)
                  VALUES('USD', 'United States dollar', '$'),
                  ('RUB', 'Russian ruble', '₽'),
                  ('TRY', 'Turkish lira', '₺'),
                  ('EUR', 'Euro', '€'),
                  ('GBP', 'Sterling', '£'),
                  ('CNY', 'Renminbi', '¥');"
INSERT_EXCHANGE_RATES="INSERT INTO ExchangeRates (BaseCurrencyId, TargetCurrencyId, Rate)
                  VALUES(1, 3, 37.95),
                  (1, 4, 0.90),
                  (2, 3, 0.45),
                  (2, 5, 0.009),
                  (4, 2, 93.38),
                  (5, 4, 1.19),
                  (6, 3, 5.20),
                  (5, 6, 9.59);"
TEST_1_DB="SELECT ID, Code, FullName, Sign FROM Currencies;"
TEST_2_DB="SELECT ID, BaseCurrencyId, TargetCurrencyId, Rate FROM ExchangeRates;"

echo $CREATE_CURRENCIES | sqlite3 $DB_NAME
echo $CREATE_EXCHANGE_RATES | sqlite3 $DB_NAME
echo $INSERT_CURRENCIES | sqlite3 $DB_NAME
echo $INSERT_EXCHANGE_RATES | sqlite3 $DB_NAME
echo "Currencies"
echo $TEST_1_DB | sqlite3 $DB_NAME
echo "ExchangeRates"
echo $TEST_2_DB | sqlite3 $DB_NAME